### ISSUE TITLE
lambda example for compression

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-javascript#1249]
We haven't tested the new compression extension on Lambda yet. A user reported that there were some issues with getting the package-lock.json file to be correct for the target operating system, and then when they deployed to lambda they got this error:

```
{
    "timestamp": "2024-04-24T15:25:04.685Z",
    "level": "ERROR",
    "message": {
        "errorType": "ImportModuleError",
        "errorMessage": "Error: Cannot find module '@mongodb-js/zstd'\nRequire stack:\n- /var/task/asset.js\n- /var/runtime/index.mjs",
        "stackTrace": [
            "Runtime.ImportModuleError: Error: Cannot find module '@mongodb-js/zstd'",
            "Require stack:",
            "- /var/task/asset.js",
            "- /var/runtime/index.mjs",
            "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
            "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
            "    at async start (file:///var/runtime/index.mjs:1282:23)",
            "    at async file:///var/runtime/index.mjs:1288:1"
        ]
    }
}
```

They said that they had to add some excludes in order to get it to deploy:

```
- '@mongodb-js/zstd'
- '@mongodb-js/zstd-darwin-arm64'
- '@mongodb-js/zstd-linux-x64-gnu'
- '@mongodb-js/zstd-linux-x64-musl'
```

But I suspect that excluding the main `zstd` package would cause the error above.

We need to either:
* come up with some automated solution during install that will sort out the correct values for a given architecture, or
* add some information to the docs/examples showing how to configure it successfully for a target architecture

If we find that the packaging for this particular zstd library is problematic, we can change to a different one; it should be possible to do that without breaking any APIs.

**Comment by cprice404** [comment]
@bruuuuuuuce let's keep this open until we have augmented Nate's docs to include a link to it or whatever?
