### ISSUE TITLE
DEADLINE_EXCEEDED seen when a client is not allow-listed for data structures.

### ISSUE THREAD

**Issue by virratanasangpunth** [momentohq/client-sdk-javascript#166]
To repro, try running an integ test with `TEST_AUTH_TOKEN` that is not allowed for datastructures Caches. You should see timeout as the failure for the integ tests for Set datastructure operations.

We expect to see `UNAVAILABLE` instead of a timeout. This ticket is created to make sure that we're error-handling correctly.

Some stacktrace from Schwern:

```
  console.log
    Response {
      _innerException: TimeoutError: 4 DEADLINE_EXCEEDED: undefined
          at Object.callErrorFromStatus (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/call.ts:81:17)
          at Object.onReceiveStatus (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/client.ts:358:36)
          at /Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/call-stream.ts:210:27
          at Object.onReceiveStatus (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/client-interceptors.ts:163:5)
          at InterceptingListenerImpl.onReceiveStatus (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/call-stream.ts:206:19)
          at /Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/call-stream.ts:210:27
          at Object.onReceiveStatus (/Volumes/Momento/client-sdk-javascript/src/grpc/retry-interceptor.ts:119:23)
          at Object.onReceiveStatus (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
          at Object.onReceiveStatus (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
          at /Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
      for call at
          at ScsClient.makeUnaryRequest (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/client.ts:328:30)
          at ScsClient.SetFetch (/Volumes/Momento/client-sdk-javascript/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
          at ScsClient.SetFetch (/Volumes/Momento/client-sdk-javascript/node_modules/@gomomento/generated-types/dist/cacheclient.js:5104:26)
          at /Volumes/Momento/client-sdk-javascript/src/internal/cache-client.ts:175:38
          at new Promise (<anonymous>)
          at CacheClient.sendSetFetch (/Volumes/Momento/client-sdk-javascript/src/internal/cache-client.ts:174:18)
          at CacheClient.setFetch (/Volumes/Momento/client-sdk-javascript/src/internal/cache-client.ts:163:23)
          at SimpleCacheClient.setFetch (/Volumes/Momento/client-sdk-javascript/src/simple-cache-client.ts:130:25)
          at Object.<anonymous> (/Volumes/Momento/client-sdk-javascript/integration/simple-cache-client.test.ts:382:44)
          at Promise.then.completed (/Volumes/Momento/client-sdk-javascript/node_modules/jest-circus/build/utils.js:391:28) {
        _transportDetails: MomentoErrorTransportDetails { grpc: [MomentoGrpcErrorDetails] },
        _errorCode: 'TIMEOUT_ERROR',
        _messageWrapper: "The client's configured timeout was exceeded; you may need to use a Configuration with more lenient timeouts"
      }
    }
```

**Comment by virratanasangpunth** [comment]
When I use the raw grpc client I don't observe issue. Therefore I think this is an issue with our js-sdk error handling, somehow.

See the repro here between raw grpc client vs our sdk client behavior: https://github.com/momentohq/client-sdk-javascript/commit/31509565050faa6d2290763c26502bc7b9077b88#diff-1bdc5d17bfc1bc846f40ce1c29c5a6e99671290226c926e487ea13cc2b4ce5e4

Ran with this auth token that is not allow-listed
```
TEST_AUTH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2aXIrdGVzdHRpbWVvdXRAbW9tZW50b2hxLmNvbSIsImNwIjoiY29udHJvbC5jZWxsLWFscGhhLWRldi5wcmVwcm9kLmEubW9tZW50b2hxLmNvbSIsImMiOiJjYWNoZS5jZWxsLWFscGhhLWRldi5wcmVwcm9kLmEubW9tZW50b2hxLmNvbSJ9.21tnkggPWsJ7wrYWJYNyLoDs-gP7NWCnIiqctXpd_Gu6LjMsGeuv-IwujwBAQRksXqbnr1NCj5qmrLUUvF-gTw npm run integration -- --silent=false
```

Then I saw that we got a timeout error instead of unavailable:

```
> @gomomento/sdk@0.0.1 integration
> jest --config jest-integration.config.ts --silent=false

 FAIL  integration/error-handling-repro.test.ts (6.479 s)
  Integration tests for convenience operations on sets datastructure
    ✓ i should see unavailable instead of deadline_exceeded with raw client (6 ms)
    ✕ i should see unavailable instead of deadline_exceeded with our sdk client (5018 ms)

  ● Integration tests for convenience operations on sets datastructure › i should see unavailable instead of deadline_exceeded with our sdk client

    expect(received).toEqual(expected) // deep equality

    Expected: "SERVER_UNAVAILABLE"
    Received: "TIMEOUT_ERROR"

      52 |     );
      53 |     expect(addResponse).toBeInstanceOf(CacheSetAddElement.Error);
    > 54 |     expect((addResponse as CacheSetRemoveElement.Error).errorCode()).toEqual(
         |                                                                      ^
      55 |       MomentoErrorCode.SERVER_UNAVAILABLE
      56 |     );
      57 |   });

      at Object.<anonymous> (integration/error-handling-repro.test.ts:54:70)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        6.523 s, estimated 7 s
Ran all test suites.
```

**Comment by virratanasangpunth** [comment]
Okay, apparently if I commented out the retryinterceptor, like this one: https://github.com/momentohq/client-sdk-javascript/commit/f36e2984850f5ca89321b0dec1ec97ca43a53636 , then the tests will pass. Therefore I think there's a bug in the RetryInterceptor.

Ran: `TEST_AUTH_TOKEN=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2aXIrdGVzdHRpbWVvdXRAbW9tZW50b2hxLmNvbSIsImNwIjoiY29udHJvbC5jZWxsLWFscGhhLWRldi5wcmVwcm9kLmEubW9tZW50b2hxLmNvbSIsImMiOiJjYWNoZS5jZWxsLWFscGhhLWRldi5wcmVwcm9kLmEubW9tZW50b2hxLmNvbSJ9.21tnkggPWsJ7wrYWJYNyLoDs-gP7NWCnIiqctXpd_Gu6LjMsGeuv-IwujwBAQRksXqbnr1NCj5qmrLUUvF-gTw npm run integration -- --silent=false`

and the tests start passing now:
```
 PASS  integration/error-handling-repro.test.ts
  Integration tests for convenience operations on sets datastructure
    ✓ i should see unavailable instead of deadline_exceeded with raw client (3 ms)
    ✓ i should see unavailable instead of deadline_exceeded with our sdk client (53 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.385 s, estimated 2 s
Ran all test suites.
```
