### ISSUE TITLE
TypeError Channel credentials must be a ChannelCredentials object

### ISSUE THREAD

**Issue by 1N50MN14** [momentohq/client-sdk-javascript#645]
Standard client initialization 

```javascript
const client = new CacheClient({
  configuration: process.env.NODE_ENV == 'production'
    ? Configurations.InRegion.Default.latest()
    : Configurations.Laptop.v1(),

  credentialProvider: CredentialProvider.fromEnvironmentVariable({
    environmentVariableName:  "MOMENTO_AUTH_TOKEN",
  }),

  defaultTtlSeconds: 60 * 60 * 24 * 30
});
```
throws

```
/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/generated-types/node_modules/@grpc/grpc-js/build/src/channel.js:28
            throw new TypeError('Channel credentials must be a ChannelCredentials object');
                  ^
TypeError: Channel credentials must be a ChannelCredentials object
    at new ChannelImplementation (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/generated-types/node_modules/@grpc/grpc-js/build/src/channel.js:28:19)
    at new Client (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/generated-types/node_modules/@grpc/grpc-js/build/src/client.js:65:36)
    at new ServiceClientImpl (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/generated-types/node_modules/@grpc/grpc-js/build/src/make-client.js:58:5)
    at new ScsControlClient (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/generated-types/dist/controlclient.js:1084:13)
    at IdleGrpcClientWrapper.clientFactoryFn (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/sdk/dist/src/internal/control-client.js:33:36)
    at new IdleGrpcClientWrapper (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/sdk/dist/src/internal/grpc/idle-grpc-client-wrapper.js:24:28)
    at new ControlClient (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/sdk/dist/src/internal/control-client.js:32:30)
    at new CacheClient (/home/am/dev/dfv/platform/api/api/node_modules/@gomomento/sdk/dist/src/cache-client.js:21:31)
    at new Cache (/home/am/dev/dfv/platform/api/api/modules/cache/index.js:22:19)
    at start (/home/am/dev/dfv/platform/api/api/index.js:138:27)

Node.js v18.12.1
```

For some odd reason when I run the above as standalone minimalist snippet it works just fine, but seems to fail when importing `@google-cloud/*` modules, I'm not sure if that's directly related or whether loading time of other modules causes the constructor to fail. The intention is to run this within GCP Run / Lambda like environment.

EDIT: Never mind it has nothing to do with ^ I'm still not sure what causes the error.

**Comment by 1N50MN14** [comment]
Found the issue, I had an outdated `@grpc/grpc-js` dependency used by another module. Manually overriding to ensure compatibility. Closing issue for now.
