### ISSUE TITLE
[Bug] Cannot set value without explicit ttl

### ISSUE THREAD

**Issue by allenheltondev** [momentohq/client-sdk-javascript#919]
If I run this code, I get the error listed at the bottom.

```javascript
const client =  await CacheClient.create({
   credentialProvider: CredentialProvider.fromEnvironmentVariable({environmentVariableName: 'MOMENTO_AUTH'}),
   configuration: Configurations.Laptop.latest(),
   defaultTtl: 300
 });

  const cacheClient  = client.cache('chatgpt');
  const r = await cacheClient.set('image', 'data');
```

**Error:**
/home/runner/MomentoCollections/node_modules/@gomomento/sdk/dist/src/internal/cache-data-client.js:173
        this.logger.trace(`Issuing 'set' request; key: ${key.toString()}, value length: ${value.length}, ttl: ${ttlToUse.toString()}`);
                                
TypeError: Cannot read properties of undefined (reading 'toString')
    at CacheDataClient.set (/home/runner/MomentoCollections/node_modules/@gomomento/sdk/dist/src/internal/cache-data-client.js:173:122)
    at CacheClient.set (/home/runner/MomentoCollections/node_modules/@gomomento/sdk-core/dist/src/internal/clients/cache/AbstractCacheClient.js:88:29)
    at MomentoCache.set (/home/runner/MomentoCollections/node_modules/@gomomento/sdk-core/dist/src/internal/clients/cache/momento-cache.js:13:33)
    at run (/home/runner/MomentoCollections/index.js:13:31)
    at Object.<anonymous> (/home/runner/MomentoCollections/index.js:20:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

**Thoughts**
I think `ttlToUse` is not being populated if not explicitly provided.

**SDK Version**
v1.39.3

**Comment by cprice404** [comment]
There is a test that I believe covers this:

https://github.com/momentohq/client-sdk-javascript/blob/0786a62855f78725e57135a075b4d15ab1c4c70e/packages/common-integration-tests/src/get-set-delete.ts#L238-L249

So I'm not quite sure what's going on here, but we can try to repro, this would definitely be an urgent bug to fix :)

**Comment by cprice404** [comment]
This turned out to be an issue with a constructor argument name (`defaultTtl` instead of `defaultTtlSeconds`). Updated #649 to add explicit runtime checks for constructor arguments for JS users.
